/*
 * Copyright (c) 2026 Contributors to the Eclipse Foundation.
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package org.eclipse.daanse.rolap.mapping.instance.emf.complex.foodmart;

import java.util.List;

import org.eclipse.daanse.cwm.testkit.api.DatabaseCheckSuiteSupplier;
import org.eclipse.daanse.cwm.testkit.api.dbcheck.DatabaseCheckSuite;
import org.eclipse.daanse.cwm.testkit.api.dbcheck.DatabaseColumnCheck;
import org.eclipse.daanse.cwm.testkit.api.dbcheck.DatabaseSchemaCheck;
import org.eclipse.daanse.cwm.testkit.api.dbcheck.DatabaseTableCheck;

public class FoodmartDatabaseCheckSuiteSupplier implements DatabaseCheckSuiteSupplier {

    @Override
    public DatabaseCheckSuite get() {
        return new DatabaseCheckSuite(
                "Database Schema Check for Foodmart",
                List.of(new DatabaseSchemaCheck("", List.of(
                        table("sales_fact_1997",
                                col("time_id", "INTEGER"),
                                col("store_id", "INTEGER"),
                                col("customer_id", "INTEGER"),
                                col("promotion_id", "INTEGER"),
                                col("product_id", "INTEGER"),
                                col("unit_sales", "DECIMAL"),
                                col("store_sales", "DECIMAL"),
                                col("store_cost", "DECIMAL")),
                        table("sales_fact_1998",
                                col("product_id", "INTEGER"),
                                col("time_id", "INTEGER"),
                                col("customer_id", "INTEGER"),
                                col("promotion_id", "INTEGER"),
                                col("store_id", "INTEGER"),
                                col("store_sales", "DECIMAL"),
                                col("store_cost", "DECIMAL"),
                                col("unit_sales", "DECIMAL")),
                        table("time_by_day",
                                col("time_id", "INTEGER"),
                                col("the_date", "TIMESTAMP"),
                                col("the_year", "SMALLINT"),
                                col("quarter", "VARCHAR"),
                                col("the_month", "VARCHAR")),
                        table("store",
                                col("store_id", "INTEGER"),
                                col("store_name", "VARCHAR"),
                                col("store_country", "VARCHAR"),
                                col("store_state", "VARCHAR"),
                                col("store_city", "VARCHAR")),
                        table("store_ragged",
                                col("store_id", "INTEGER"),
                                col("store_type", "VARCHAR"),
                                col("store_name", "VARCHAR"),
                                col("store_street_address", "VARCHAR"),
                                col("store_state", "VARCHAR"),
                                col("store_country", "VARCHAR"),
                                col("store_manager", "VARCHAR"),
                                col("store_city", "VARCHAR"),
                                col("store_sqft", "INTEGER"),
                                col("grocery_sqft", "INTEGER"),
                                col("frozen_sqft", "INTEGER"),
                                col("meat_sqft", "INTEGER"),
                                col("coffee_bar", "SMALLINT"),
                                col("region_id", "INTEGER")),
                        table("customer",
                                col("customer_id", "INTEGER"),
                                col("fullname", "VARCHAR"),
                                col("gender", "VARCHAR"),
                                col("country", "VARCHAR"),
                                col("state_province", "VARCHAR"),
                                col("city", "VARCHAR")),
                        table("product",
                                col("product_id", "INTEGER"),
                                col("product_name", "VARCHAR"),
                                col("brand_name", "VARCHAR")),
                        table("promotion",
                                col("promotion_id", "INTEGER"),
                                col("promotion_name", "VARCHAR"),
                                col("media_type", "VARCHAR")),
                        table("warehouse",
                                col("warehouse_id", "INTEGER"),
                                col("warehouse_name", "VARCHAR"),
                                col("warehouse_city", "VARCHAR"),
                                col("warehouse_state_province", "VARCHAR"),
                                col("warehouse_country", "VARCHAR")),
                        table("inventory_fact_1997",
                                col("product_id", "INTEGER"),
                                col("time_id", "INTEGER"),
                                col("warehouse_id", "INTEGER"),
                                col("store_id", "INTEGER"),
                                col("units_ordered", "INTEGER"),
                                col("units_shipped", "INTEGER"),
                                col("warehouse_sales", "DECIMAL"),
                                col("warehouse_cost", "DECIMAL"),
                                col("supply_time", "INTEGER"),
                                col("store_invoice", "DECIMAL")),
                        table("employee",
                                col("employee_id", "INTEGER"),
                                col("full_name", "VARCHAR"),
                                col("first_name", "VARCHAR"),
                                col("last_name", "VARCHAR"),
                                col("position_id", "INTEGER"),
                                col("position_title", "VARCHAR"),
                                col("store_id", "INTEGER"),
                                col("supervisor_id", "INTEGER"),
                                col("salary", "DECIMAL")),
                        table("employee_closure",
                                col("supervisor_id", "INTEGER"),
                                col("employee_id", "INTEGER"),
                                col("distance", "INTEGER")),
                        table("department",
                                col("department_id", "INTEGER"),
                                col("department_description", "VARCHAR")),
                        table("position",
                                col("position_id", "INTEGER"),
                                col("position_title", "VARCHAR"),
                                col("pay_type", "VARCHAR"),
                                col("min_scale", "DECIMAL"),
                                col("max_scale", "DECIMAL")),
                        table("salary",
                                col("employee_id", "INTEGER"),
                                col("department_id", "INTEGER"),
                                col("pay_date", "TIMESTAMP"),
                                col("salary_paid", "DECIMAL"),
                                col("overtime_paid", "DECIMAL"),
                                col("vacation_accrued", "REAL"),
                                col("vacation_used", "REAL")),
                        table("agg_c_special_sales_fact_1997",
                                col("product_id", "INTEGER"),
                                col("promotion_id", "INTEGER"),
                                col("customer_id", "INTEGER"),
                                col("store_id", "INTEGER"),
                                col("time_month", "SMALLINT"),
                                col("time_quarter", "VARCHAR"),
                                col("time_year", "SMALLINT"),
                                col("store_sales_sum", "DECIMAL"),
                                col("store_cost_sum", "DECIMAL"),
                                col("unit_sales_sum", "DECIMAL"),
                                col("fact_count", "INTEGER")),
                        table("agg_c_10_sales_fact_1997",
                                col("month_of_year", "SMALLINT"),
                                col("quarter", "VARCHAR"),
                                col("the_year", "SMALLINT"),
                                col("store_sales", "DECIMAL"),
                                col("store_cost", "DECIMAL"),
                                col("unit_sales", "DECIMAL"),
                                col("customer_count", "INTEGER"),
                                col("fact_count", "INTEGER")),
                        table("agg_l_05_sales_fact_1997",
                                col("product_id", "INTEGER"),
                                col("customer_id", "INTEGER"),
                                col("promotion_id", "INTEGER"),
                                col("store_id", "INTEGER"),
                                col("store_sales", "DECIMAL"),
                                col("store_cost", "DECIMAL"),
                                col("unit_sales", "DECIMAL"),
                                col("fact_count", "INTEGER")),
                        table("agg_l_03_sales_fact_1997",
                                col("time_id", "INTEGER"),
                                col("customer_id", "INTEGER"),
                                col("store_sales", "DECIMAL"),
                                col("store_cost", "DECIMAL"),
                                col("unit_sales", "DECIMAL"),
                                col("fact_count", "INTEGER")),
                        table("agg_pl_01_sales_fact_1997",
                                col("product_id", "INTEGER"),
                                col("time_id", "INTEGER"),
                                col("customer_id", "INTEGER"),
                                col("store_sales_sum", "DECIMAL"),
                                col("store_cost_sum", "DECIMAL"),
                                col("unit_sales_sum", "DECIMAL"),
                                col("fact_count", "INTEGER")),
                        table("agg_g_ms_pcat_sales_fact_1997",
                                col("gender", "VARCHAR"),
                                col("marital_status", "VARCHAR"),
                                col("month_of_year", "SMALLINT"),
                                col("quarter", "VARCHAR"),
                                col("the_year", "SMALLINT"),
                                col("store_sales", "DECIMAL"),
                                col("store_cost", "DECIMAL"),
                                col("unit_sales", "DECIMAL"),
                                col("customer_count", "INTEGER"),
                                col("fact_count", "INTEGER")),
                        table("agg_c_14_sales_fact_1997",
                                col("product_id", "INTEGER"),
                                col("customer_id", "INTEGER"),
                                col("store_id", "INTEGER"),
                                col("promotion_id", "INTEGER"),
                                col("month_of_year", "SMALLINT"),
                                col("quarter", "VARCHAR"),
                                col("the_year", "SMALLINT"),
                                col("store_sales", "DECIMAL"),
                                col("store_cost", "DECIMAL"),
                                col("unit_sales", "DECIMAL"),
                                col("fact_count", "INTEGER"))))),
                List.of());
    }

    private static DatabaseTableCheck table(String name, DatabaseColumnCheck... cols) {
        return new DatabaseTableCheck(name, List.of(cols));
    }

    private static DatabaseColumnCheck col(String name, String type) {
        return new DatabaseColumnCheck(name, type);
    }
}
