/*
 * Copyright (c) 2026 Contributors to the Eclipse Foundation.
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package org.eclipse.daanse.rolap.mapping.instance.emf.complex.csdl.bikeaccessories;

import java.util.List;

import org.eclipse.daanse.cwm.testkit.api.DatabaseCheckSuiteSupplier;
import org.eclipse.daanse.cwm.testkit.api.dbcheck.DatabaseCheckSuite;
import org.eclipse.daanse.cwm.testkit.api.dbcheck.DatabaseColumnCheck;
import org.eclipse.daanse.cwm.testkit.api.dbcheck.DatabaseSchemaCheck;
import org.eclipse.daanse.cwm.testkit.api.dbcheck.DatabaseTableCheck;

public class BikeAccessoriesDatabaseCheckSuiteSupplier implements DatabaseCheckSuiteSupplier {

    @Override
    public DatabaseCheckSuite get() {
        return new DatabaseCheckSuite(
                "Database Schema Check for BikeAccessories",
                List.of(new DatabaseSchemaCheck("", List.of(
                        table("Fact",
                                col("RowNumber", "INTEGER"),
                                col("ProductKey", "INTEGER"),
                                col("OrderDateKey", "INTEGER"),
                                col("DueDateKey", "INTEGER"),
                                col("ShipDateKey", "INTEGER"),
                                col("CustomerKey", "INTEGER"),
                                col("PromotionKey", "INTEGER"),
                                col("CurrencyKey", "INTEGER"),
                                col("SalesTerritoryKey", "INTEGER"),
                                col("SalesOrderNumber", "INTEGER"),
                                col("SalesOrderLineNumber", "VARCHAR"),
                                col("RevisionNumber", "INTEGER"),
                                col("OrderQuantity", "INTEGER"),
                                col("UnitPrice", "INTEGER"),
                                col("ExtendedAmount", "DECIMAL"),
                                col("UnitPriceDiscountPct", "DECIMAL"),
                                col("DiscountAmount", "DOUBLE"),
                                col("ProductStandardCost", "DOUBLE"),
                                col("TotalProductCost", "DECIMAL"),
                                col("SalesAmount", "DECIMAL"),
                                col("TaxAmt", "DECIMAL"),
                                col("Freight", "DECIMAL"),
                                col("CarrierTrackingNumber", "VARCHAR"),
                                col("CustomerPONumber", "VARCHAR"),
                                col("EmployeeKey", "INTEGER"),
                                col("BillingCustomerKey", "INTEGER"),
                                col("StoreKey", "INTEGER"),
                                col("TotalSales", "INTEGER")),
                        table("Customer",
                                col("RowNumber", "INTEGER"),
                                col("CustomerKey", "INTEGER"),
                                col("GeographyKey", "INTEGER"),
                                col("CustomerAlternateKey", "VARCHAR"),
                                col("FirstName", "VARCHAR"),
                                col("MiddleName", "VARCHAR"),
                                col("LastName", "VARCHAR"),
                                col("NameStyle", "BOOLEAN"),
                                col("BirthDate", "DATE"),
                                col("MaritalStatus", "VARCHAR"),
                                col("Suffix", "VARCHAR"),
                                col("Gender", "VARCHAR"),
                                col("EmailAddress", "VARCHAR"),
                                col("YearlyIncome", "DECIMAL"),
                                col("TotalChildren", "INTEGER"),
                                col("NumberChildrenAtHome", "INTEGER"),
                                col("EnglishEducation", "VARCHAR"),
                                col("SpanishEducation", "VARCHAR"),
                                col("FrenchEducation", "VARCHAR"),
                                col("EnglishOccupation", "VARCHAR"),
                                col("SpanishOccupation", "VARCHAR"),
                                col("FrenchOccupation", "VARCHAR"),
                                col("HouseOwnerFlag", "VARCHAR"),
                                col("NumberCarsOwned", "VARCHAR"),
                                col("AddressLine1", "VARCHAR"),
                                col("AddressLine2", "VARCHAR"),
                                col("Phone", "VARCHAR"),
                                col("DateFirstPurchase", "DATE"),
                                col("CommuteDistance", "VARCHAR")),
                        table("Employee",
                                col("RowNumber", "INTEGER"),
                                col("EmployeeKey", "INTEGER"),
                                col("ParentEmployeeKey", "INTEGER"),
                                col("EmployeeNationalIDAlternateKey", "VARCHAR"),
                                col("ParentEmployeeNationalIDAlternateKey", "VARCHAR"),
                                col("SalesTerritoryKey", "INTEGER"),
                                col("FirstName", "VARCHAR"),
                                col("LastName", "VARCHAR"),
                                col("MiddleName", "VARCHAR"),
                                col("NameStyle", "BOOLEAN"),
                                col("Title", "VARCHAR"),
                                col("HireDate", "DATE"),
                                col("BirthDate", "DATE"),
                                col("LoginID", "VARCHAR"),
                                col("EmailAddress", "VARCHAR"),
                                col("Phone", "VARCHAR"),
                                col("MaritalStatus", "VARCHAR"),
                                col("EmergencyContactName", "VARCHAR"),
                                col("EmergencyContactPhone", "VARCHAR"),
                                col("SalariedFlag", "BOOLEAN"),
                                col("Gender", "VARCHAR"),
                                col("PayFrequency", "INTEGER"),
                                col("BaseRate", "DECIMAL"),
                                col("VacationHours", "INTEGER"),
                                col("SickLeaveHours", "INTEGER"),
                                col("CurrentFlag", "BOOLEAN"),
                                col("SalesPersonFlag", "BOOLEAN"),
                                col("DepartmentName", "VARCHAR"),
                                col("StartDate", "DATE"),
                                col("EndDate", "DATE"),
                                col("Status", "VARCHAR")),
                        table("Geography",
                                col("RowNumber", "INTEGER"),
                                col("GeographyKey", "INTEGER"),
                                col("City", "VARCHAR"),
                                col("StateProvinceCode", "VARCHAR"),
                                col("StateProvinceName", "VARCHAR"),
                                col("CountryRegionCode", "VARCHAR"),
                                col("EnglishCountryRegionName", "VARCHAR"),
                                col("SpanishCountryRegionName", "VARCHAR"),
                                col("FrenchCountryRegionName", "VARCHAR"),
                                col("PostalCode", "VARCHAR"),
                                col("SalesTerritoryKey", "INTEGER")),
                        table("Product",
                                col("RowNumber", "INTEGER"),
                                col("ProductKey", "INTEGER"),
                                col("ProductAlternateKey", "VARCHAR"),
                                col("ProductSubcategoryKey", "INTEGER"),
                                col("WeightUnitMeasureCode", "VARCHAR"),
                                col("SizeUnitMeasureCode", "VARCHAR"),
                                col("EnglishProductName", "VARCHAR"),
                                col("SpanishProductName", "VARCHAR"),
                                col("FrenchProductName", "VARCHAR"),
                                col("StandardCost", "DECIMAL"),
                                col("FinishedGoodsFlag", "BOOLEAN"),
                                col("Color", "VARCHAR"),
                                col("SafetyStockLevel", "INTEGER"),
                                col("ReorderPoint", "INTEGER"),
                                col("ListPrice", "DECIMAL"),
                                col("Size", "VARCHAR"),
                                col("SizeRange", "VARCHAR"),
                                col("Weight", "DOUBLE"),
                                col("DaysToManufacture", "INTEGER"),
                                col("ProductLine", "VARCHAR"),
                                col("DealerPrice", "DECIMAL"),
                                col("Class", "VARCHAR"),
                                col("Style", "VARCHAR"),
                                col("ModelName", "VARCHAR"),
                                col("EnglishDescription", "VARCHAR"),
                                col("FrenchDescription", "VARCHAR"),
                                col("ChineseDescription", "VARCHAR"),
                                col("ArabicDescription", "VARCHAR"),
                                col("HebrewDescription", "VARCHAR"),
                                col("ThaiDescription", "VARCHAR"),
                                col("StartDate", "DATE"),
                                col("EndDate", "DATE"),
                                col("Status", "VARCHAR"),
                                col("Subcategory", "VARCHAR")),
                        table("ProductCategory",
                                col("RowNumber", "INTEGER"),
                                col("ProductCategoryKey", "INTEGER"),
                                col("ProductCategoryAlternateKey", "INTEGER"),
                                col("EnglishProductCategoryName", "VARCHAR"),
                                col("SpanishProductCategoryName", "VARCHAR"),
                                col("FrenchProductCategoryName", "VARCHAR")),
                        table("ProductSubcategory",
                                col("RowNumber", "INTEGER"),
                                col("ProductSubcategoryKey", "INTEGER"),
                                col("ProductSubcategoryAlternateKey", "INTEGER"),
                                col("EnglishProductSubcategoryName", "VARCHAR"),
                                col("SpanishProductSubcategoryName", "VARCHAR"),
                                col("FrenchProductSubcategoryName", "VARCHAR"),
                                col("ProductCategoryKey", "INTEGER")),
                        table("Store",
                                col("RowNumber", "INTEGER"),
                                col("StoreKey", "INTEGER"),
                                col("Geography_Key", "INTEGER"),
                                col("StoreName", "VARCHAR"),
                                col("Number_of_Employees", "INTEGER"),
                                col("Sales", "DECIMAL")),
                        table("Time",
                                col("RowNumber", "INTEGER"),
                                col("TimeKey", "INTEGER"),
                                col("FullDateAlternateKey", "DATE"),
                                col("DayNumberOfWeek", "INTEGER"),
                                col("EnglishDayNameOfWeek", "VARCHAR"),
                                col("SpanishDayNameOfWeek", "VARCHAR"),
                                col("FrenchDayNameOfWeek", "VARCHAR"),
                                col("DayNumberOfMonth", "INTEGER"),
                                col("DayNumberOfYear", "INTEGER"),
                                col("WeekNumberOfYear", "INTEGER"),
                                col("EnglishMonthName", "VARCHAR"),
                                col("SpanishMonthName", "VARCHAR"),
                                col("FrenchMonthName", "VARCHAR"),
                                col("MonthNumberOfYear", "INTEGER"),
                                col("CalendarQuarter", "INTEGER"),
                                col("CalendarYear", "VARCHAR"),
                                col("CalendarSemester", "INTEGER"),
                                col("FiscalQuarter", "INTEGER"),
                                col("FiscalYear", "VARCHAR"),
                                col("FiscalSemester", "INTEGER"))))),
                List.of());
    }

    private static DatabaseTableCheck table(String name, DatabaseColumnCheck... cols) {
        return new DatabaseTableCheck(name, List.of(cols));
    }

    private static DatabaseColumnCheck col(String name, String type) {
        return new DatabaseColumnCheck(name, type);
    }
}
